// One-time generator for src/lib/worldmap-data.ts.
// Rasterizes public-domain country polygons into a braille-dot land bitmap.
// Run: bun scripts/generate-worldmap.ts

const SOURCE = "https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json"
const ISO_SOURCE =
  "https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json"
const WIDTH = 180
const HEIGHT = 72
const LAT_TOP = 84
const LAT_BOTTOM = -60

interface Ring {
  points: [number, number][]
  bbox: [number, number, number, number]
  country: string // ISO 3166-1 alpha-2, "" when unknown
}

function ringOf(points: [number, number][], country: string): Ring {
  let minX = Infinity
  let minY = Infinity
  let maxX = -Infinity
  let maxY = -Infinity
  for (const [x, y] of points) {
    minX = Math.min(minX, x)
    minY = Math.min(minY, y)
    maxX = Math.max(maxX, x)
    maxY = Math.max(maxY, y)
  }
  return { points, bbox: [minX, minY, maxX, maxY], country }
}

function inRing(lon: number, lat: number, ring: Ring): boolean {
  const [minX, minY, maxX, maxY] = ring.bbox
  if (lon < minX || lon > maxX || lat < minY || lat > maxY) return false
  const pts = ring.points
  let inside = false
  for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
    const [xi, yi] = pts[i]!
    const [xj, yj] = pts[j]!
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside
  }
  return inside
}

const geo = (await (await fetch(SOURCE)).json()) as {
  features: { id?: string; geometry: { type: string; coordinates: unknown } }[]
}
const isoList = (await (await fetch(ISO_SOURCE)).json()) as { "alpha-2": string; "alpha-3": string }[]
const alpha3to2 = new Map(isoList.map((c) => [c["alpha-3"], c["alpha-2"]]))

const rings: Ring[] = []
for (const feature of geo.features) {
  const country = alpha3to2.get(feature.id ?? "") ?? ""
  const { type, coordinates } = feature.geometry
  if (type === "Polygon") {
    rings.push(ringOf((coordinates as [number, number][][])[0]!, country))
  } else if (type === "MultiPolygon") {
    for (const poly of coordinates as [number, number][][][]) rings.push(ringOf(poly[0]!, country))
  }
}
console.log(`${rings.length} outer rings`)

// per-dot country index encoded as one char: " " = water, charCode 48+i = countries[i]
const countries: string[] = []
const countryIndex = new Map<string, number>()
const indexOf = (country: string): number => {
  let i = countryIndex.get(country)
  if (i === undefined) {
    i = countries.length
    countries.push(country)
    countryIndex.set(country, i)
  }
  return i
}

const rows: string[] = []
const countryRows: string[] = []
for (let y = 0; y < HEIGHT; y++) {
  const lat = LAT_TOP - ((y + 0.5) / HEIGHT) * (LAT_TOP - LAT_BOTTOM)
  let row = ""
  let countryRow = ""
  for (let x = 0; x < WIDTH; x++) {
    const lon = -180 + ((x + 0.5) / WIDTH) * 360
    const ring = rings.find((r) => inRing(lon, lat, r))
    row += ring ? "1" : "0"
    countryRow += ring ? String.fromCharCode(48 + indexOf(ring.country)) : " "
  }
  rows.push(row)
  countryRows.push(countryRow)
}
console.log(`${countries.length} countries indexed`)

const out = `// Generated by scripts/generate-worldmap.ts — do not edit by hand.
// Equirectangular land bitmap, lon -180..180, lat ${LAT_TOP}..${LAT_BOTTOM}.
export const WORLD_WIDTH = ${WIDTH}
export const WORLD_HEIGHT = ${HEIGHT}
export const WORLD_LAT_TOP = ${LAT_TOP}
export const WORLD_LAT_BOTTOM = ${LAT_BOTTOM}
export const WORLD_ROWS: string[] = [
${rows.map((r) => `  "${r}",`).join("\n")}
]
// ISO 3166-1 alpha-2 per land dot: " " = water, charCode 48+i = WORLD_COUNTRIES[i]
export const WORLD_COUNTRIES: string[] = ${JSON.stringify(countries)}
export const WORLD_COUNTRY_ROWS: string[] = [
${countryRows.map((r) => `  ${JSON.stringify(r)},`).join("\n")}
]
`
await Bun.write("src/lib/worldmap-data.ts", out)
console.log(`wrote src/lib/worldmap-data.ts (${WIDTH}x${HEIGHT})`)
